### ISSUE TITLE
Installation fails with node versions >10.19

### ISSUE THREAD

**Issue by kvakes** [windingtree/org.id-resolver#2]
# Node 12.6.1

`npm install` fails with

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/username/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.5.13-arch1-1
gyp ERR! command "/home/username/.nvm/versions/node/v12.16.1/bin/node" "/home/username/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/username/Projects/org.id-resolver/node_modules/ganache-cli/node_modules/keccak
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
```

# Node 12.6.2

`npm install` succeeds but with quite a few errors related to building keccak and scrypt

`npm link` fails with

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/username/.nvm/versions/node/v12.16.2/lib/node_modules/@windingtree/org.id-resolver/dist/cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/username/.nvm/versions/node/v12.16.2/lib/node_modules/@windingtree/org.id-resolver/dist/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by kvakes** [comment]
I haven't tested other versions of node.
